Repository houssembenali/fil_rouge, pull requests merged in 2021-07, with the labels that each got.

#33 WIP: Us 31 environnement developpement initial
  .gitignore
Labels: technical

#32 US 3 affichage des projets #3
  .gitignore
  docker/webapp/Dockerfile
  docker/webapp/src/DB/projects.txt
  docker/webapp/src/main.py
  docker/webapp/src/modules/projects/list-projet.html
  docker/webapp/src/modules/projects/listprojet.py
  docker/webapp/src/modules/template/page.html
Labels: feature

#34 WIP : environnement-developpement-initial : mise à jour du install-python.sh avec modules pythons.
  .gitignore
  vagrant/nexus/install.sh
  vagrant/nexus/vagrantfile
  vagrant/python/install_python.sh
Labels: technical

#31 Environnement de développement initial
  .gitignore
  Jenkinsfile
  docker/webapp/Dockerfile
  docker/webapp/requirements.txt
  docker/webapp/src/DB/projects.txt
  docker/webapp/src/main.py
  docker/webapp/src/modules/projects/list-projet.html
  docker/webapp/src/modules/projects/listprojet.py
  docker/webapp/src/modules/template/page.html
  vagrant/jenkins/install.sh
  vagrant/jenkins/vagrantfile
  vagrant/nexus/install.sh
  vagrant/nexus/vagrantfile
  vagrant/python/install_python.sh
  vagrant/python/vagrantfile
Labels: feature, technical
